version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "2140:2140"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "2141:2141"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped 